name: Continuous Integration Workflow
on:
  push:
    branches: [ master, develop, feature/** ]
  pull_request:
    branches: [ develop ]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and yarn
        uses: eriksape/actions/packages/node-12-setup@main
      - name: Run Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and yarn
        uses: eriksape/actions/packages/node-12-setup@main
      - name: Run tests
        run: npm run test:cov
